# https://wiki.debian.org/DebianRepository/UseThirdParty
# https://support.torproject.org/apt/tor-deb-repo/

---
- name: check for keyring
  ansible.builtin.stat:
    path: /usr/share/keyrings/deb.torproject.org-keyring.gpg
  register: keyring

- name: download initial keyring
  ansible.builtin.get_url:
    url: https://deb.torproject.org/torproject.org/A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89.asc
    dest: /usr/share/keyrings/deb.torproject.org-keyring.gpg
    checksum: sha256:2318eb0aa0349a1f111421ba0ffd949da805cf4fda6d915f80710144955d5774
    # Fingerprint: A3C4 F0F9 79CA A22C DBA8  F512 EE8C BC9E 886D DD89
  when: not keyring.stat.exists

- name: remove old repository
  ansible.builtin.apt_repository:
    repo: deb http://deb.torproject.org/torproject.org {{ tor_dist }} main
    state: absent

- name: add repository
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/deb.torproject.org-keyring.gpg] http://deb.torproject.org/torproject.org {{ tor_dist }} main

- name: install keyring
  ansible.builtin.apt:
    name: deb.torproject.org-keyring
