# https://wiki.debian.org/DebianRepository/UseThirdParty
# https://support.torproject.org/apt/tor-deb-repo/

---
- name: check for keyring
  stat:
    path: /usr/share/keyrings/deb.torproject.org-keyring.gpg
  register: keyring

- name: download initial keyring
  get_url:
    url: https://deb.torproject.org/torproject.org/A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89.asc
    dest: /usr/share/keyrings/deb.torproject.org-keyring.gpg
    checksum: sha256:7b3fec7e6928ec67c6342a78ed9b2d647d034d0d01c9dd17864f4d7c04bf1347
    # Fingerprint: A3C4 F0F9 79CA A22C DBA8  F512 EE8C BC9E 886D DD89
  when: not keyring.stat.exists

- name: remove old repository
  apt_repository:
    repo: deb http://deb.torproject.org/torproject.org {{ tor_dist }} main
    state: absent

- name: add repository
  apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/deb.torproject.org-keyring.gpg] http://deb.torproject.org/torproject.org {{ tor_dist }} main

- name: install keyring
  apt:
    name: deb.torproject.org-keyring
