---
- name: install extra packages
  apt:
    name: "{{ tor_packages_extra }}"
  when: tor_packages_extra | list

- name: configure Tor Project repository
  include: configure-repository.yml
  when: tor_repository

- name: install tor
  include: install-tor.yml

- name: create bridge instances
  include: create-instance.yml
  vars:
    type: bridge
  loop: "{{ tor_instances_bridge }}"
  loop_control:
    loop_var: instance
  tags: [bridge-relays]

- name: create middle instances
  include: create-instance.yml
  vars:
    type: middle
  loop: "{{ tor_instances_middle }}"
  loop_control:
    loop_var: instance
  tags: [middle-relays]

- name: create exit instances
  include: create-instance.yml
  vars:
    type: exit
  loop: "{{ tor_instances_exit }}"
  loop_control:
    loop_var: instance
  tags: [exit-relays]
