---
- name: install extra packages
  ansible.builtin.apt:
    name: "{{ tor_packages_extra }}"
  when: tor_packages_extra | list

- name: configure Tor Project repository
  ansible.builtin.include_tasks: configure-repository.yml
  when: tor_repository

- name: install tor
  ansible.builtin.include_tasks: install-tor.yml

- name: remove instances
  ansible.builtin.include_tasks: remove-instance.yml
  loop: "{{ tor_instances_remove }}"
  loop_control:
    loop_var: name
  tags: [remove-instances]

- name: create bridge instances
  ansible.builtin.include_tasks: create-instance.yml
  vars:
    type: bridge
  loop: "{{ tor_instances_bridge }}"
  loop_control:
    loop_var: instance
  tags: [bridge-instances, tor-instances]

- name: create middle instances
  ansible.builtin.include_tasks: create-instance.yml
  vars:
    type: middle
  loop: "{{ tor_instances_middle }}"
  loop_control:
    loop_var: instance
  tags: [middle-instances, tor-instances]

- name: create exit instances
  ansible.builtin.include_tasks: create-instance.yml
  vars:
    type: exit
  loop: "{{ tor_instances_exit }}"
  loop_control:
    loop_var: instance
  tags: [exit-instances, tor-instances]
