---
- name: stop service
  ansible.builtin.systemd:
    name: tor@{{ name }}
    state: stopped

- name: remove user
  ansible.builtin.user:
    name: _tor-{{ name }}
    state: absent
    remove: true

- name: remove files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/tor/instances/{{ name }}
    - /etc/systemd/system/tor@{{ name }}.service

- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
